from django.urls import path
from . import views

urlpatterns = [
    path('posts',views.posts_list),
    path('posts/subs/<int:sub>/<int:ind>/',views.posts_sub),
    path('posts/<auth>/<int:ind>/',views.posts_auth),
    path('subs',views.subs_list),
    path('fastsubs',views.bus_list),
    path('auths',views.auth_list),
    path('listvideo',views.videos_list),
    path('listvideo/subs/<int:sub>/<int:ind>/',views.videos_sub),
    path('listvideo/<auth>/<int:ind>/',views.videos_auth),
    path('feed',views.feed),
    path('feed/<int:sub>/',views.feedsub),
    path('feed/<auth>/',views.feedauth),
    path('deletep',views.unseep),
    path('deletev',views.delete_videos),
    path('delp/<int:pk>/',views.del_p),
    path('delv/<int:pk>/',views.del_v),
    path('likep/<int:pk>/',views.like_p),
    path('likev/<int:pk>/',views.like_v),
    path('dlikep/<int:pk>/',views.dlike_p),
    path('dlikev/<int:pk>/',views.dlike_v),
    path('subr',views.subgrid),
    path('authr',views.authgrid),
    path('newsub',views.add_sub),
    path('newauth',views.add_auth),
    path('delsub/<int:pk>/',views.delsub),
    path('delauth/<auth>/',views.delauth),
    path('refre/<int:pk>/',views.refre),
    path('refrea/<auth>/',views.refrea),
    path('comp/<int:sub>/<int:ind>/',views.videos_comp),
    path('comp/<auth>/<int:ind>/',views.videos_acomp),
    path('p/<int:pk>',views.post_det),
    path('v/<int:pk>',views.vid_det),
    path('updates',views.upo),
    path('up/<tit>/',views.ups),
    path('uplo/',views.uplouplo),
    path('look/<search>/',views.lookit),
    path('search/posts/<search>/',views.posto_search),
    path('search/listvideo/<search>/',views.videoo_search),
    ]